version: '3.8'

services:

#Сторонняя система



#Api для взаимодействия с базой данных
  erthsobesapi:
    image: erthsobes/erthsobesapi
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:6570
    build:
      context: .
      dockerfile: erthsobesapi/Dockerfile
    ports:
      - "6570:6570"
    networks:
       my-network:
          ipv4_address: 172.23.0.2


networks:
  my-network:
    external: true
