

--
-- TOC entry 204 (class 1259 OID 16473)
-- Name: Attachments; Type: TABLE; Schema: public; Owner: orders
--

CREATE TABLE IF NOT EXISTS public."Attachments" (
    id bigint NOT NULL,
    hash text NOT NULL
);


ALTER TABLE public."Attachments" OWNER TO orders;

--
-- TOC entry 203 (class 1259 OID 16471)
-- Name: Attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: orders
--

ALTER TABLE public."Attachments" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Attachments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 16483)
-- Name: Order_info; Type: TABLE; Schema: public; Owner: orders
--

CREATE TABLE IF NOT EXISTS public."Order_info" (
    id bigint NOT NULL,
    product_id uuid NOT NULL,
    type text,
    cost numeric NOT NULL,
    "phoneNumber" text,
    email text,
    value text,
    attachment_id bigint NOT NULL
);


ALTER TABLE public."Order_info" OWNER TO orders;

--
-- TOC entry 205 (class 1259 OID 16481)
-- Name: Order_info_id_seq; Type: SEQUENCE; Schema: public; Owner: orders
--

ALTER TABLE public."Order_info" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Order_info_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 16466)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: orders
--

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO orders;

--
-- TOC entry 2923 (class 0 OID 16473)
-- Dependencies: 204
-- Data for Name: Attachments; Type: TABLE DATA; Schema: public; Owner: orders
--



--
-- TOC entry 2925 (class 0 OID 16483)
-- Dependencies: 206
-- Data for Name: Order_info; Type: TABLE DATA; Schema: public; Owner: orders
--



--
-- TOC entry 2921 (class 0 OID 16466)
-- Dependencies: 202
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: orders
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20201119223525_ordersMigration', '5.0.0');


--
-- TOC entry 2932 (class 0 OID 0)
-- Dependencies: 203
-- Name: Attachments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: orders
--

SELECT pg_catalog.setval('public."Attachments_id_seq"', 1, false);


--
-- TOC entry 2933 (class 0 OID 0)
-- Dependencies: 205
-- Name: Order_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: orders
--

SELECT pg_catalog.setval('public."Order_info_id_seq"', 1, false);


--
-- TOC entry 2790 (class 2606 OID 16470)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2792 (class 2606 OID 16480)
-- Name: Attachments PK_attachments; Type: CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public."Attachments"
    ADD CONSTRAINT "PK_attachments" PRIMARY KEY (id);


--
-- TOC entry 2794 (class 2606 OID 16490)
-- Name: Order_info PK_order_info; Type: CONSTRAINT; Schema: public; Owner: orders
--

ALTER TABLE ONLY public."Order_info"
    ADD CONSTRAINT "PK_order_info" PRIMARY KEY (id);



-- Completed on 2020-11-21 23:09:52

--
-- PostgreSQL database dump complete
--

